# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Parking Reservation' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Parking Reservation
  pod 'AFNetworking'
  pod 'Bolts'
  pod 'Mantle'
  pod 'Fabric'
  pod 'Crashlytics'

end
